sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxb8ec569c56bfbb88
    secret: b9daff583b7ac281c49374b868a4c082
    mchid: 1561414331
    mch-serial-no: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    private-key-file-path: privateKeyFile.pem
    api-v3-key: CZBK51236435wxpay435434323FFDUV3
    we-chat-pay-cert-file-path: weChatPayCertFile.pem
    notify-url: http://6e9c2d32.r9.cpolar.cn/notify/paysuccess
    refund-notify-url: http://6e9c2d32.r9.cpolar.cn/notify/refundsuccess